#********** Driver Parameters ************

/proc_underwater_com/settings/role : "a"

/proc_underwater_com/settings/channel : "4"

/proc_underwater_com/settings/number_mission : 16

/proc_underwater_com/settings/id : 8